// Generated by scripts/recovery/generate-shims.mjs — a compat shim: no logic, only the owner's exports under the old names.
import { createForm, renderWith } from "obix-core-component";
export { createForm } from "obix-core-component";
export type { FieldState, FormConfig, FormState, ValidationState } from "obix-core-component";
export const renderForm = renderWith(createForm);
